config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'pages#home'
  # get 'about', to:'pages#about'
  resources :articles

  # RESTful routes for the users
  get 'signup', to: 'users#new'
  get '/user/:id/edit', to: 'users#edit', as: 'edit_user'
  get '/user/:id', to: 'users#show', as: 'user'
  patch '/user/:id', to: 'users#update'
  delete '/user/:id', to: 'users#destroy'
  resources :users, only: %i[index create]

  # Sessions routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Categories routes
  resources :categories, except: %i[destroy]
end

app/models/article.rb
# frozen_string_literal: true

# Basic model Article user dependent
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# Controller for Articles routes
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :require_user, except: %i[show index]
  before_action :require_same_user, only: %i[edit update destroy]

  # GET method for individual article, passing id as paramether. /artiles/:id
  def show; end

  # GET method for the articles index. | /articles
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  # GET method for the creation of articles. | /articles/new
  def new
    # That instance is necessary since the view utilizes it to find possible errors.
    @article = Article.new
  end

  # GET method for editing articles. | /articles/:id/edit
  def edit; end

  # POST method for the articles. | /articles
  def create
    # As we receive the data from the user, we need to whitelist it and the require and permit do that.
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      # Send a flash message for the component in the main application.
      flash[:notice] = 'Article was created successfully!'
      redirect_to @article
    else
      # In case of error the page is reloaded and the variable keeps the error message, displaying in the view.
      render 'new'
    end
  end

  # PATCH/PUT method for the article edit. | /articles/:id
  def update
    # Updating using the update method whitelisting the params given by the user.
    if @article.update(article_params)
      flash[:notice] = 'The article was updated successfully!'
      redirect_to @article
    else
      render 'edit'
    end
  end

  # DELETE method | /articles/:id
  def destroy
    @article.destroy
    redirect_to articles_path, status: :see_other
  end

  # Everything bellow it is exclusive to this controller and cannot be used outside of it.
  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    return unless current_user != @article.user && !current_user.admin?

    flash[:alert] = 'You can only edit or delete your own articles'
    redirect_to @article
  end
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-body rounded">
          <div class="card-header fst-italic">
            By <%= link_to article.user.username, user_path(article.user.id) %>
            <% if article.categories.any? %>
              <div class="mt-2"><%= render article.categories %></div>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to  article.title, article_path(article.id), class: "text-success text-decoration-none" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to  "View", article_path(article.id), class: "btn btn-outline-success" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to  "Edit", edit_article_path(article.id), class: "btn btn-outline-primary" %>
              <%= link_to  "Delete", article_path(article.id), class: "btn btn-outline-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, edited
              <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <!-- Using form helper to create a form using the model object -->
  <div class="row justify-content-center">
    <div class="col-10">
      <!-- Embedding ruby to iterate an possible error -->
      <%= render 'shared/errors', obj: @article %>
      <!-- -->
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-secondary rounded", local: true, data: { turbo: false }) do |form| %>
        <div class="mb-3 row">
          <%= form.label :title, class: "col-sm-2 col-form-label text-white" %>
          <div class="col-sm-10">
            <%= form.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>
        <!-- -->
        <div class="mb-3 row">
          <%= form.label :description, class: "col-sm-2 col-form-label text-white" %>
          <div class="col-sm-10">
            <%= form.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>
        <!-- -->
        <div class="mb-3 row">
          <%= form.label :category, class: "col-sm-2 col-form-label text-white" %>
          <div class="col-sm-10">
            <%= form.collection_select :category_ids, Category.all, :id, :name,
            { prompt: "Please select a category bellow (can be empty) " },
            { multiple: true, size: 3, class: "form-select shadow rounded"} %>
          </div>
        </div>
        <!-- -->
        <div class="form-group text-center">
          <%= form.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <!-- -->
    <div class="text-center mt-1 mb-4">
      <%= link_to 'Cancel and return to articles', articles_path, class: "btn btn-outline-dark" %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class= "text-center mt-4">Listing all articles</h1>
<!-- -->

<!-- <%= will_paginate @articles %> -->
<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'article' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class= "text-center mt-4"><%= @article.title %></h2>
<!-- -->
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-body rounded">
        <div class="card-header fst-italic">
          By <%= @article.user.username %>
          <%= link_to gravatar_for(@article.user), user_path(@article.user.id) %>
          <% if @article.categories.any? %>
            <div class="mt-2"><%= render @article.categories %></div>
          <% end %>
        </div>
        <div class="card-body">
          <div class="card-text text-start"><%= simple_format(@article.description) %></div>
          <% if logged_in? && (@article.user == current_user || current_user.admin?)%>
            <%= link_to  "Edit", edit_article_path(@article.id), class: "btn btn-outline-primary" %>
            <%= link_to  "Delete", article_path(@article.id), class: "btn btn-outline-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago, edited
            <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
</div>