config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'pages#home'
  # get 'about', to:'pages#about'
  resources :articles

  # RESTful routes for the users
  get 'signup', to: 'users#new'
  get '/user/:id/edit', to: 'users#edit', as: 'edit_user'
  get '/user/:id', to: 'users#show', as: 'user'
  patch '/user/:id', to: 'users#update'
  delete '/user/:id', to: 'users#destroy'
  resources :users, only: %i[index create]

  # Sessions routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Categories routes
  resources :categories, except: %i[destroy]
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# A controller to implement categories on the app
class CategoriesController < ApplicationController
  before_action :require_admin, except: %i[index show]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category was successfully created.'
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = 'Category was successfully updated.'
      redirect_to @category
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    return if logged_in? && current_user.admin?

    flash[:alert] = 'Only admins can perform that action.'
    redirect_to categories_path
  end
end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill mr-1 custom-badge" %>

app/views/categories/_form.html.erb
<!-- Calling the component that iterate a possible error -->
<%= render 'shared/errors', obj: @category %>
<!-- -->
<%= form_with(model: @category, class: "shadow p-3 mb-3 bg-secondary rounded", local: true, data: { turbo: false }) do |form| %>
  <div class="mb-3 row">
    <%= form.label :name, "Category name", class: "col-sm-2 col-form-label text-white" %>
    <div class="col-sm-10">
      <%= form.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
    </div>
  </div>
  <!-- -->
  <div class="form-group text-center">
    <%= form.submit class: "btn btn-outline-light btn-lg" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Update category</h1>
<div class="container">
  <!-- Using form helper to create a form using the model object -->
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render  "form" %>
    </div>
    <!-- -->
    <div class="text-center mt-1 mb-4">
      <%= link_to 'Cancel and return to category', category_path(@category.id), class: "btn btn-outline-dark" %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<!-- <%= will_paginate @categories %> -->
<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-body rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to  category.name, category_path(category.id), class: "text-success text-decoration-none" %></h5>
            <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago, edited
              <%= time_ago_in_words(category.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a new category</h1>
<div class="container">
  <!-- Using form helper to create a form using the model object -->
  <div class="row justify-content-center">
    <div class="col-10">
      <!-- Calling the component that iterate a possible error -->
      <%= render 'shared/errors', obj: @category %>
      <!-- -->
      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-secondary rounded", local: true, data: { turbo: false }) do |form| %>
        <div class="mb-3 row">
          <%= form.label :name, "Category name", class: "col-sm-2 col-form-label text-white" %>
          <div class="col-sm-10">
            <%= form.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
          </div>
        </div>
        <!-- -->
        <div class="form-group text-center">
          <%= form.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <!-- -->
    <div class="text-center mt-1 mb-4">
      <%= link_to 'Cancel and return to articles', articles_path, class: "btn btn-outline-dark" %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to  "Edit category name", edit_category_path(@category.id), class: "btn btn-outline-primary" %>
  </div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>

<!-- Add pagination to articles listing on user profile -->
<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render  "articles/article" %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>
<!-- End of pagination -->