config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'pages#home'
  # get 'about', to:'pages#about'
  resources :articles

  # RESTful routes for the users
  get 'signup', to: 'users#new'
  get '/user/:id/edit', to: 'users#edit', as: 'edit_user'
  get '/user/:id', to: 'users#show', as: 'user'
  patch '/user/:id', to: 'users#update'
  delete '/user/:id', to: 'users#destroy'
  resources :users, only: %i[index create]

  # Sessions routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Categories routes
  resources :categories, except: %i[destroy]
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to  "Igor Renan", "https://github.com/Igorenansc/alpha-blog", class: "text-white text-decoration-none" %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to  "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <!-- <a class="nav-link disabled">Disabled</a> -->
          <%= link_to  "Bloggers", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to  "View articles", articles_path, class: "dropdown-item" %></li>
            <% if logged_in? %>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to  "Create new article", new_article_path, class: "dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to  "View categories", categories_path, class: "dropdown-item" %></li>
            <% if logged_in? && current_user.admin? %>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to  "Create new category", new_category_path, class: "dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= '(Admin)' if current_user.admin? %> <%= current_user.username %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to  "View Profile", user_path(current_user.id), class: "dropdown-item" %></li>
              <li><%= link_to  "Edit Profile", edit_user_path(current_user.id), class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to  "Delete your account", user_path(current_user.id), class: "dropdown-item text-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure?\nAll your articles will be deleted too." } %></li>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to  "Logout", logout_path, class: "nav-link", data: { turbo_method: :delete } %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to  "Log in", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to  "Sign up", signup_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body class="d-flex flex-column">
    <%= render 'layouts/navigation'%>
    <div id="page-content">
      <%= render 'layouts/messages'%>
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>